package com.healthiera.mobile.entity.enumeration;

/**
 * @author Davit Ter-Arakelyan
 * @date 22.10.2016
 */

public enum HealthDateType {
    OBESTY,
    THIRSTY,
    PROFUSE_SWEATING,
    NOCTURIA,
    POLYURIA,
    POLYDIPSIA,
    BULIMIA,
    BULIMIA_FATHER,
    BULIMIA_MOTHER,
    BULIMIA_GF,
    BULIMIA_GM,
    DIABET_MELITUS_FATHER,
    DIABET_MELITUS_MOTHER,
    DIABET_MELITUS_GF,
    DIABET_MELITUS_GM,
    GLUCOCRITICOIDS_INTAKE,
    GLUCOCRITICOIDS_INTAKE_START_DATE,
    GLUCOCRITICOIDS_INTAKE_END_DATE,
    GLUCOCRITICOIDS_INTAKE_HORMONE,
    HYPERTENSION,
    BIM,
    WEIGHT,
    THALLIUM_HIPSE,
    PULSE,
    BLOOD_PRESSURE,
    GLUCOSE_TOLERANCE_TEST,
    GLUCOSE_LEVEL_IN_URINE
}
